# -*- coding: utf-8 -*-
"""API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRDoJ5YglDaL0fayjmY7-xkj1B-56P0Z
"""

import cv2
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub

def transfer_style(content_image, style_image, model_path):
    size_threshold = 2000
    resizing_shape = (1000, 1000)
    content_shape = content_image.shape
    style_shape = style_image.shape

    if content_shape[0] > size_threshold or content_shape[1] > size_threshold:
        content_image = cv2.resize(content_image, resizing_shape)
    if style_shape[0] > size_threshold or style_shape[1] > size_threshold:
        style_image = cv2.resize(style_image, resizing_shape)

    content_image = content_image.astype(np.float32)[np.newaxis, ...] / 255.
    style_image = style_image.astype(np.float32)[np.newaxis, ...] / 255.
    style_image = tf.image.resize(style_image, (256, 256))

    hub_module = hub.load(model_path)
    outputs = hub_module(tf.constant(content_image), tf.constant(style_image))
    stylized_image = outputs[0]
    stylized_image = np.squeeze(stylized_image, axis=0)
    return stylized_image