# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cb6clX0_zYalfaxAQZqNzl3hgcWN9xgP
"""

import streamlit as st
from PIL import Image
import numpy as np
from io import BytesIO
from API import transfer_style

st.title(\"🪄Neural Style Transfer-Pixlate🦋\")

st.markdown(\"Turn your photo into art! Just upload a Content Image and a Style Image to get started.\")

content_image = st.file_uploader(\"Upload Content Image\", type=['png', 'jpg', 'jpeg'])
style_image = st.file_uploader(\"Upload Style Image\", type=['png', 'jpg', 'jpeg'])

if content_image and style_image:
    with st.spinner(\"Applying Style Transfer...\"):
        content = np.array(Image.open(content_image))
        style = np.array(Image.open(style_image))
        model_path = \"https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2\"
        result = transfer_style(content, style, model_path)

        result_image = Image.fromarray((result * 255).astype(np.uint8))
        st.image(result_image, caption=\"Stylized Output\")

        buf = BytesIO()
        result_image.save(buf, format=\"PNG\")
        st.download_button(\"Download Image\", buf.getvalue(), file_name=\"stylized_output.png\", mime=\"image/png\")